pipeline {
  
  agent {
    docker {
      image 'maven:3-alpine'
      args '-v /root/.m2:/root/.ms'
    }
  }
  
  stages{
    stage('Build'){
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
    }
  }
  
}
